name: TinyTimer
main: amata1219.tiny.timer.TinyTimer
version: 1.0.0
api-version: 1.13
author: amata1219(Twitter@amata1219)

commands:
  timer:
    description: timer command.
    usage: /<command>
    permission: tiny.timer.timer
    permission-message: You do not have permission.
  timer+:
    description: timer plus command.
    usage: /<command>
    permission: tiny.timer.timer.plus
    permission-message: You do not have permission.